"""ADDED_SIZE_COLUMN

Revision ID: 6ba466f70a96
Revises: 2a8281019c4f
Create Date: 2023-07-16 20:40:52.144850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba466f70a96'
down_revision = '2a8281019c4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'size')
    # ### end Alembic commands ###
